try:
    from python.MODULES import *
except:
    from MODULES import *

def CREATE_TABLES():
    CREATE_TABLE_USER()
    CREATE_TABLE_CATEGORIES()
    CREATE_TABLE_POST()
    CREATE_TABLE_POST_CATEGORY()
    CREATE_TABLE_TAGS()
    CREATE_TABLE_LIKES()
    CREATE_TABLE_DISLIKES()
    CREATE_TABLE_FAVOURITES()
    CREATE_TABLE_COMMENTS()
    CREATE_TABLE_VIEWS()
    CREATE_TABLE_CONNECTIONS()
    CREATE_TABLE_IP_ADRESSES()
    CREATE_TABLE_CHAT_ROOMS()
    CREATE_TABLE_CHAT_ADMINS()
    CREATE_TABLE_CHAT_USERS()
    # BLOCKS
    # REQUESTS
    # TAG REQUESTS
    # POST REQUESTS
    # CATEGORY REQUESTS
    
def FULL_RESET():
    CREATE_TABLES()
    
if __name__ == "__main__":
    FULL_RESET()